require("impatient").enable_profile()

-- Better Notifications
vim.notify = require("notify")

require("core.options")
require("core.keymaps")
require("core.autocommands")
require("colors.colorscheme")
require("colors.highlights")
require("plugins")
require("plugins.configs.cmp")
require("plugins.configs.lsp")
require("plugins.configs.telescope")
require("plugins.configs.treesitter")
require("plugins.configs.autopairs")
require("plugins.configs.comment")
require("plugins.configs.gitsigns")
require("plugins.configs.nvim-tree")
require("plugins.configs.bufferline")
require("plugins.configs.lualine")
require("plugins.configs.toggleterm")
require("plugins.configs.alpha")
require("plugins.configs.which-key")
require("plugins.configs.better-escape")
require("plugins.configs.mini")
require("plugins.configs.nvim-colorizer")
