vim.highlight.create("StatusLine", {guibg = "NONE"}, false)
vim.highlight.create("StatusLineNC", {guibg = "NONE"}, false)
vim.highlight.create("MiniTrailspace", {guibg = "#FF2020"}, false)
vim.highlight.create("CustomDashboardHeader", {guifg = "#6E6C7E"}, false)
vim.highlight.create("CustomDashboardFooter", {guifg = "#37FF8B"}, false)
vim.highlight.create("CustomDashboardButtons", {guifg = "#C1B8C8"}, false)
